#!/bin/bash
# Refresh per-country and per-ASN IP blocklists used by nginx.
# Invoked weekly by /etc/systemd/system/hlp-blocklist-refresh.timer
# (see server/systemd/). Can also be run manually as root.
set -e

mkdir -p /etc/nginx/blocklists

# 1. Country lists from ipdeny.com (Singapore, China, Vietnam).
#    To add a country, append "<code>:/etc/nginx/blocklists/<code>.zone"
#    to COUNTRIES below; the code must match an ipdeny aggregated file.
COUNTRIES=(
    "sg:/etc/nginx/blocklists/sg.zone"
    "cn:/etc/nginx/blocklists/cn.zone"
    "vn:/etc/nginx/blocklists/vn.zone"
)
for entry in "${COUNTRIES[@]}"; do
    code="${entry%%:*}"
    dest="${entry##*:}"
    tmp=$(mktemp)
    if curl -sf "https://www.ipdeny.com/ipblocks/data/aggregated/${code}-aggregated.zone" -o "$tmp" && [ -s "$tmp" ]; then
        mv "$tmp" "$dest"
    else
        rm -f "$tmp"
        echo "WARN: failed to download ${code}-aggregated.zone, keeping previous $dest" >&2
    fi
done

# 2. Bot ASN routes from RADB (Byteplus, Tencent, Zenlayer).
TMP_ASN=$(mktemp)
> "$TMP_ASN"
for asn in 150436 132203 4229; do
    whois -h whois.radb.net -- "-i origin AS$asn" 2>/dev/null | awk "/^route:/ {print \$2}" >> "$TMP_ASN"
done
sort -u "$TMP_ASN" -o "$TMP_ASN"
if [ -s "$TMP_ASN" ]; then
    mv "$TMP_ASN" /etc/nginx/blocklists/bot-asns.zone
else
    rm -f "$TMP_ASN"
    echo "WARN: RADB returned no routes, keeping previous bot-asns.zone" >&2
fi

# 3. Regenerate the geo config from all lists.
{
    echo "# Auto-regenerated by hlp-blocklist-refresh.service"
    echo "# Geo-block: matches incoming \$remote_addr against country-level (SG, CN, VN)"
    echo "# and bot-ASN-level (Byteplus, Tencent Cloud, Zenlayer) CIDR lists."
    echo "geo \$blocked_country {"
    echo "    default 0;"
    for entry in "${COUNTRIES[@]}"; do
        dest="${entry##*:}"
        [ -s "$dest" ] && awk "{print \"    \" \$1 \" 1;\"}" "$dest"
    done
    [ -s /etc/nginx/blocklists/bot-asns.zone ] && awk "{print \"    \" \$1 \" 1;\"}" /etc/nginx/blocklists/bot-asns.zone
    echo "}"
} > /etc/nginx/conf.d/01-country-block.conf

nginx -t && systemctl reload nginx
