#!/bin/bash
# Refresh per-country and per-ASN IP blocklists used by nginx. Runs weekly.
set -e

TMP_SG=$(mktemp)
TMP_ASN=$(mktemp)

# 1. Country list (Singapore) from ipdeny.com
if curl -sf https://www.ipdeny.com/ipblocks/data/aggregated/sg-aggregated.zone -o "$TMP_SG" && [ -s "$TMP_SG" ]; then
    mv "$TMP_SG" /etc/nginx/blocklists/sg.zone
fi

# 2. Bot ASN routes from RADB (Byteplus, Tencent, Zenlayer)
> "$TMP_ASN"
for asn in 150436 132203 4229; do
    whois -h whois.radb.net -- "-i origin AS$asn" 2>/dev/null | awk "/^route:/ {print \$2}" >> "$TMP_ASN"
done
sort -u "$TMP_ASN" -o "$TMP_ASN"
if [ -s "$TMP_ASN" ]; then
    mv "$TMP_ASN" /etc/nginx/blocklists/bot-asns.zone
fi

# 3. Regenerate the geo config from both lists
{
    echo "# Auto-regenerated by /etc/cron.weekly/refresh-country-blocklist"
    echo "geo \$blocked_country {"
    echo "    default 0;"
    awk "{print \"    \" \$1 \" 1;\"}" /etc/nginx/blocklists/sg.zone
    awk "{print \"    \" \$1 \" 1;\"}" /etc/nginx/blocklists/bot-asns.zone
    echo "}"
} > /etc/nginx/conf.d/01-country-block.conf

nginx -t && systemctl reload nginx
