import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-sqlite'

// Data fix: four section slugs contained diacritical characters (ö, ü),
// carried over from the original import rather than generated by the slug
// hook. Next.js does not percent-decode dynamic route params, so the route
// handler received the literal "g%C3%B6bekli-tepe" and the `slug equals`
// lookup never matched — every one of these pages 404'd in production.
//
// Renaming them to plain ASCII resolves that. All four are leaf sites with
// no child sections, so the slug only appears in two places per section:
// its own `sections.slug` value and the trailing segment of its own
// `sections_breadcrumbs.url` row. Both are updated here. The redirect maps
// and sitemap regenerate from the DB on deploy, so they pick up the new
// slugs automatically. No external redirects are needed because the old
// accented URLs already 404'd (no inbound link or indexed page to preserve).
//
//   575  göbekli-tepe                 -> gobekli-tepe
//   587  letoönletoon                 -> letoon
//   3618 süleymaniye-complex-istanbul -> suleymaniye-complex-istanbul
//   3642 miniatürk-scale-models       -> miniaturk-scale-models

const RENAMES: Array<{ id: number; from: string; to: string }> = [
  { id: 575, from: 'göbekli-tepe', to: 'gobekli-tepe' },
  { id: 587, from: 'letoönletoon', to: 'letoon' },
  { id: 3618, from: 'süleymaniye-complex-istanbul', to: 'suleymaniye-complex-istanbul' },
  { id: 3642, from: 'miniatürk-scale-models', to: 'miniaturk-scale-models' },
]

async function rename(
  db: MigrateUpArgs['db'],
  id: number,
  from: string,
  to: string,
): Promise<void> {
  await db.run(sql`UPDATE sections SET slug = ${to} WHERE id = ${id};`)
  // The section's own breadcrumb row stores the slug as the final path
  // segment of its url (e.g. ".../eastern-turkey/göbekli-tepe").
  await db.run(
    sql`UPDATE sections_breadcrumbs
        SET url = REPLACE(url, ${'/' + from}, ${'/' + to})
        WHERE doc_id = ${id} AND url LIKE ${'%/' + from};`,
  )
}

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const { id, from, to } of RENAMES) {
    await rename(db, id, from, to)
  }
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  for (const { id, from, to } of RENAMES) {
    // Reverse: swap `to` and `from`.
    await rename(db, id, to, from)
  }
}
