#!/usr/bin/env python3
"""
Generate src/redirect-maps.generated.ts — section/page ID → slug lookup
tables that the middleware uses to resolve old ASP URLs without needing
runtime DB access (the libsql Edge bundle does not support file: URLs).

Run on EC2 immediately before `npm run build` so the deployed bundle has
a fresh snapshot of the live database.

Usage:
    python3 scripts/generate_redirect_maps.py
"""

import json
import os
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
OUT_PATH = ROOT / "src" / "redirect-maps.generated.ts"


def load_env():
    if not ENV_PATH.exists():
        return
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, val = line.split("=", 1)
            os.environ.setdefault(key.strip(), val.strip())


def open_db():
    db_url = os.environ["DATABASE_URL"]
    if not db_url.startswith("file:"):
        raise SystemExit(
            f"Only file: DATABASE_URL is supported by this script (got {db_url!r}). "
            "If you move to remote Turso, extend this script to use libsql_experimental."
        )
    path = db_url[len("file:"):]
    if not path.startswith("/"):
        path = str(ROOT / path.lstrip("./"))
    return sqlite3.connect(path)


def main():
    load_env()
    db = open_db()

    section_slugs = {}
    for sid, slug in db.execute("SELECT id, slug FROM sections WHERE slug IS NOT NULL"):
        section_slugs[sid] = slug

    page_slugs = {}
    for pid, slug in db.execute("SELECT id, slug FROM pages WHERE slug IS NOT NULL"):
        page_slugs[pid] = slug

    lines = [
        "// AUTO-GENERATED by scripts/generate_redirect_maps.py — do not edit by hand.",
        "// Run the script (manually or via deploy.sh) to refresh from the live database.",
        "",
        "export const SECTION_SLUGS: Readonly<Record<number, string>> = "
        + json.dumps(section_slugs, sort_keys=True, indent=2)
        + ";",
        "",
        "export const PAGE_SLUGS: Readonly<Record<number, string>> = "
        + json.dumps(page_slugs, sort_keys=True, indent=2)
        + ";",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines))
    print(
        f"Wrote {OUT_PATH.relative_to(ROOT)} — "
        f"{len(section_slugs)} sections, {len(page_slugs)} pages"
    )


if __name__ == "__main__":
    main()
