#!/usr/bin/env python3
"""
Generate src/redirect-maps.generated.ts — section/page ID → slug lookup
tables that the middleware uses to resolve old ASP URLs without needing
runtime DB access (the libsql Edge bundle does not support file: URLs).

Run on EC2 immediately before `npm run build` so the deployed bundle has
a fresh snapshot of the live database.

Usage:
    python3 scripts/generate_redirect_maps.py
"""

import json
import os
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
OUT_PATH = ROOT / "src" / "redirect-maps.generated.ts"


def load_env():
    if not ENV_PATH.exists():
        return
    for line in ENV_PATH.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, val = line.split("=", 1)
            os.environ.setdefault(key.strip(), val.strip())


def open_db():
    db_url = os.environ["DATABASE_URL"]
    if not db_url.startswith("file:"):
        raise SystemExit(
            f"Only file: DATABASE_URL is supported by this script (got {db_url!r}). "
            "If you move to remote Turso, extend this script to use libsql_experimental."
        )
    path = db_url[len("file:"):]
    if not path.startswith("/"):
        path = str(ROOT / path.lstrip("./"))
    return sqlite3.connect(path)


def main():
    load_env()
    db = open_db()

    # Skip unpublished sections so their legacy /go.asp?s=N or
    # /browse.asp?SiteID=N URLs land on /gone instead of redirecting to a
    # section page that the public would 404 on.
    #
    # SECTION_SLUGS is keyed by the modern section_ID (== sections.id) and
    # used for ?s= URLs. LEGACY_SITE_SLUGS / LEGACY_SUBREGION_SLUGS are
    # keyed by section_Old_ID (sections.legacy_old_id) and used for
    # ?SiteID= and ?SubRegionID= URLs respectively — the old site used a
    # different ID system for those params.
    section_slugs = {}
    legacy_site_slugs = {}
    legacy_subregion_slugs = {}
    for sid, slug, section_type, legacy_old_id in db.execute(
        "SELECT id, slug, section_type, legacy_old_id FROM sections "
        "WHERE slug IS NOT NULL AND (published IS NULL OR published != 0)"
    ):
        section_slugs[sid] = slug
        if legacy_old_id is None:
            continue
        if section_type == "site":
            legacy_site_slugs[int(legacy_old_id)] = slug
        elif section_type == "region":
            legacy_subregion_slugs[int(legacy_old_id)] = slug

    page_slugs = {}
    for pid, slug in db.execute("SELECT id, slug FROM pages WHERE slug IS NOT NULL"):
        page_slugs[pid] = slug

    lines = [
        "// AUTO-GENERATED by scripts/generate_redirect_maps.py — do not edit by hand.",
        "// Run the script (manually or via deploy.sh) to refresh from the live database.",
        "",
        "export const SECTION_SLUGS: Readonly<Record<number, string>> = "
        + json.dumps(section_slugs, sort_keys=True, indent=2)
        + ";",
        "",
        "export const LEGACY_SITE_SLUGS: Readonly<Record<number, string>> = "
        + json.dumps(legacy_site_slugs, sort_keys=True, indent=2)
        + ";",
        "",
        "export const LEGACY_SUBREGION_SLUGS: Readonly<Record<number, string>> = "
        + json.dumps(legacy_subregion_slugs, sort_keys=True, indent=2)
        + ";",
        "",
        "export const PAGE_SLUGS: Readonly<Record<number, string>> = "
        + json.dumps(page_slugs, sort_keys=True, indent=2)
        + ";",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines))
    print(
        f"Wrote {OUT_PATH.relative_to(ROOT)} — "
        f"{len(section_slugs)} sections, "
        f"{len(legacy_site_slugs)} legacy sites, "
        f"{len(legacy_subregion_slugs)} legacy subregions, "
        f"{len(page_slugs)} pages"
    )


if __name__ == "__main__":
    main()
